### ISSUE TITLE
Difference in specification between Haxe and ES6 String trimming

### ISSUE THREAD

**Issue by back2dos** [explorigin/es6-externs#1]
The ES6 spec demands non-breaking spaces to be trimmed, while Haxe does not. Consider this assertion:

```
assertEquals(1, String.fromCharCode(0xA0).trim().length);
```

With es6-hx it no longer holds. Given the semantics of non-breaking spaces, I would actually argue that  the Haxe behavior makes more sense.

What really matters though, is that it should be consistent between all platforms.

**Comment by back2dos** [comment]
I have conducted some benchmarking of my own, because you refuse to, on grounds that elude me:

**Comment by back2dos** [comment]
I have conducted some benchmarking of my own, because you refuse to, on grounds that elude me: https://gist.github.com/back2dos/3720c7bacfe099c92a4f

It seems that the standard library is in fact already faster if there are no whitespaces to be trimmed. The code is to be found here: https://github.com/back2dos/es6-hx/blob/master/test-bench/BenchmarkTrim.hx

The first number is your version, the second is the standard lib, and the third one is a version I've optimized against this particular benchmark. Whether the benchmark itself measures something useful is a good question. I'd happily try to make it more real-worldy, if you have any suggestions.

But if we assume it is representative, then your intuition about using native code was wrong. So again: effective performance optimization requires measurement.

On that same assumption, the last implementation might be a good addition. It is often faster, and rarely more than 100% slower than the native versions. And it is consistent with the Haxe standard library. I'd really rather not have string trimming give me different results on the php/neko server and the js client.

**Comment by explorigin** [comment]
> I have conducted some benchmarking of my own, because you refuse to, on grounds that elude me...

See this is not a nice thing to say.  I never refused.  I have other obligations in life and work on this in what time I have and as I enjoy it.

I'll comment more when I have some time to study the results and code.  In the meantime, I'll ask this question: Even though the ES6 trim does not meet the Haxe spec, it is still very useful for front-end development.  Should it be exposed some other way other than 

`(untyped "trim my spaces   ").trim()`  ?

**Comment by back2dos** [comment]
I would suggest putting it in `js.Lib.trim` with a `@:require(es6)` or something.

Which just made me thing that It might make sense to introduce a `-D es=<version>` (or whatever the name) flag, so that one can do `@:require(es >= 6)` and `#if es >= 6`.

**Comment by explorigin** [comment]
I stick by my original "common sense" that ES5 String.trim() is the correct decision.  I believe it to the fastest implementation in the majority of cases.  I can say this because I believe you have made two critical errors in your testing code.
1. Sometimes JS engines can optimize out critical steps in testing if the functions are too simple.  The V8 engine is most known for this.  The V8 engine (Chrome and Node) is also the one that has the most prominent disadvantages from the native trim method according to your test.  By making the tests more like real-world code (not just throwing away the results), we get a better test.
2. You have based your position on the advantage of the V8 engine whereas the native trim method is faster in both Firefox and IE (mostly even in your flawed test).  I posit that the combination of Firefox and IE comprise the majority of the marketshare of desktop web browsers and therefore should carry the weight when choosing the best method (http://www.netmarketshare.com/browser-market-share.aspx?qprid=0&qpcustomd=0).  There is a question here about mobile browser marketshare.

I have some code already that has brought me to these conclusions but I'm not yet ready to share.  I want to see if I can eliminate GC-pause that is muddying some test results.  I also want to compare with mobile browsers.

There is also the outstanding question about whether or not String.trim() is appropriate for Haxe.  I'm undecided as to how to handle that yet with this project.

**Comment by explorigin** [comment]
I've posted my code changes here: https://github.com/back2dos/es6-hx/compare/master...explorigin:test-bench?expand=1

The conclusion is not clear cut.  I only tested in the listed browsers currently.  Here are some numbers (summary at the bottom):

Firefox 38:
BenchmarkTrim.hx:76: Trimming 1250000 times with an average of 0 whitespaces
BenchmarkTrim.hx:100: 0.039999961853027344s (native)
BenchmarkTrim.hx:100: 0.03600001335144043s (std)
BenchmarkTrim.hx:100: 0.03500008583068848s (both)
BenchmarkTrim.hx:76: Trimming 258500 times with an average of 10 whitespaces
BenchmarkTrim.hx:100: 0.017000198364257812s (native)
BenchmarkTrim.hx:100: 0.019999980926513672s (std)
BenchmarkTrim.hx:100: 0.016000032424926758s (both)
BenchmarkTrim.hx:76: Trimming 142000 times with an average of 50 whitespaces
BenchmarkTrim.hx:100: 0.021000146865844727s (native)
BenchmarkTrim.hx:100: 0.039999961853027344s (std)
BenchmarkTrim.hx:100: 0.03500008583068848s (both)
BenchmarkTrim.hx:76: Trimming 74000 times with an average of 500 whitespaces
BenchmarkTrim.hx:100: 0.042999982833862305s (native)
BenchmarkTrim.hx:100: 0.17999982833862305s (std)
BenchmarkTrim.hx:100: 0.16000008583068848s (both)

Chrome :
BenchmarkTrim.hx:76: Trimming 1250000 times with an average of 0 whitespaces
BenchmarkTrim.hx:100: 0.17499995231628418s (native)
BenchmarkTrim.hx:100: 0.18000006675720215s (std)
BenchmarkTrim.hx:100: 0.14100003242492676s (both)
BenchmarkTrim.hx:76: Trimming 258500 times with an average of 10 whitespaces
BenchmarkTrim.hx:100: 0.0690000057220459s (native)
BenchmarkTrim.hx:100: 0.09400010108947754s (std)
BenchmarkTrim.hx:100: 0.06399989128112793s (both)
BenchmarkTrim.hx:76: Trimming 142000 times with an average of 50 whitespaces
BenchmarkTrim.hx:100: 0.06100010871887207s (native)
BenchmarkTrim.hx:100: 0.06599998474121094s (std)
BenchmarkTrim.hx:100: 0.06200003623962402s (both)
BenchmarkTrim.hx:76: Trimming 74000 times with an average of 500 whitespaces
BenchmarkTrim.hx:100: 0.11899995803833008s (native)
BenchmarkTrim.hx:100: 0.18600010871887207s (std)
BenchmarkTrim.hx:100: 0.15199995040893555s (both)

IE 11:
BenchmarkTrim.hx:76: Trimming 1250000 times with an average of 0 whitespaces
BenchmarkTrim.hx:100: 0.2760008245239258s (native)
BenchmarkTrim.hx:100: 0.3149998188018799s (std)
BenchmarkTrim.hx:100: 0.23199987411499023s (both)
BenchmarkTrim.hx:76: Trimming 258500 times with an average of 10 whitespaces
BenchmarkTrim.hx:100: 0.10200003051757812s (native)
BenchmarkTrim.hx:100: 0.30500006675720215s (std)
BenchmarkTrim.hx:100: 0.11699986457824707s (both)
BenchmarkTrim.hx:76: Trimming 142000 times with an average of 50 whitespaces
BenchmarkTrim.hx:100: 0.13199996948242187s (native)
BenchmarkTrim.hx:100: 0.5290000438690185s (std)
BenchmarkTrim.hx:100: 0.20800018310546875s (both)
BenchmarkTrim.hx:76: Trimming 74000 times with an average of 500 whitespaces
BenchmarkTrim.hx:100: 0.5249998569488525s (native)
BenchmarkTrim.hx:100: 2.4709999561309814s (std)
BenchmarkTrim.hx:100: 0.8480000495910644s (both)

Summary:
In every case over 50 whitespaces, native wins (in IE and Firefox, sometimes dramatically so).  However 0 and 10 are the more likely real-world cases.  In those cases, your "both" method wins by a small margin except for IE where it loses by a small margin at 10 whitespaces.

Conclusion:
In most of the cases, the difference between winning and losing is small enough to not make performance a significant deciding factor because it depends on your workload, customer profile etc.  However, what is clear is that the existing haxe method for String.trim() should be replaced with your "both" method (since it meets the Haxe spec and ES5 trim() does not).

**Comment by explorigin** [comment]
The :100: cracked me up.  I decided not to change it.  :smile:

**Comment by explorigin** [comment]
**NOTE**: Edited after fixing a bug for Android 4 browser.

Numbers on mobile leans toward your **both** method.  Native enjoys good support on Safari and Safari is the market leading mobile browser. But Android 4.0 + Chrome claim more of the mobile market than even Safari and native performs relatively poorly there.  I'll not paste the numbers but here's the summary (in order... fastest, 2nd, slowest):

Safari on IOS 8:
0 - both, native, std
10 - native, both, std
50 - native, both, std
500 - native, both, std

Chrome on Android 5:
0 - native, std, both
10 - both, native, std
50 - both, std, native
500 - both, std, native

Android 4.0 Browser:
0 - both, std, native
10 - both, std, native
50 - both, std, native
500 - both, std, native

Firefox on Android 5:
0 - both, std, native
10 - native, both, std
50 - native, both, std
500 - native, both, std

Thoughts:
- Mobile marketshare numbers from http://www.netmarketshare.com/browser-market-share.aspx?qprid=0&qpcustomd=1
- The margin is narrow with no clear winner for all major mobile browsers.  I'd personally pick native because Android 4.0 browser support will dramatically decrease over the next few years.  Even though native performs poorly in Chrome >=50 average spaces, I feel like this is less of a real-world scenario compared to 0 and 10 average spaces.
- **Both** has good performance (except in Chrome with no whitespace) and would support all mobile browsers.  This is more support that it should replace Haxe's current Stringtools.trim() implementation (irrespective of the presence of the js_es5 flag).

**Comment by explorigin** [comment]
If you want to run this test on Android 4, you'll need to compile without the ES6 Map support since Map is not implemented there.

**Comment by explorigin** [comment]
Removed ES5 String.trim() support in b2ae30f0e51a.
